### ISSUE TITLE
Update to use NODENAME environment and node resource for AS number and IP addresses.

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-bgp-daemon#18]
Pending completion of https://github.com/projectcalico/calicoctl/pull/1453, we should update the go BGP daemon to use:
-  NODENAME environment instead of HOSTNAME
-  The IP addresses from the Node resource rather than the IP and IP6 environments.

Once that is complete, we should update calicoctl/calico_node/startup/startup.go:::writeStartupEnv to remove the inclusion of HOSTNAME, IP and IP6 from the environments file since this should no longer be required.

**Comment by ishidawataru** [comment]
I think we can close this since https://github.com/projectcalico/calico-bgp-daemon/pull/14 is merged.

**Comment by robbrockbank** [comment]
There is a small remaining amount of code to remove in startup.go.

Suggest we do this in the next release.

**Comment by bcreane** [comment]
@rob, please re-open this issue if there are remaining chores to complete (and thanks for the PR review).
