### ISSUE TITLE
BGP not configured but running

### ISSUE THREAD

**Issue by telekomancer** [projectcalico/calico-bgp-daemon#51]
I installed calico according to the documentation but i guess that BGP shouldn't be running.

## Expected Behavior

If i see the logs, i see some bgp activity and try to peer with other devices

Review bgp configuration during install

## Current Behavior

If i see the logs, i see this:

```
I0119 12:42:42.455673   19086 prober.go:112] Readiness probe for "calico-node-rszfd_kube-system(5cf624de-523b-43cd-8557-d2bbe6458f3e):calico-node" failed (failure): calico/node is not ready: BIRD is not ready: BGP not established with 192.168.31.62021-01-19 12:42:42.412 [INFO][1303] health.go 156: Number of node(s) with BGP peering established = 0
```

No bgp activity

## Possible Solution

First, don't start BGP and second, fix the log line.

... **BGP not established with 192.168.31.62021-01-19** ...

## Steps to Reproduce (for bugs)

1. Just install kubernetes, rancher and use as CNI, Calico
2. You'll see in logs, bgp activities

## Context

- Not affected by this issue
- Try to improve logs and communication/services

## Your Environment

* Calico-node/calicoctl version: container{Container{Name:calico-kube-controllers,Image:rancher/calico-kube-controllers:v3.13.4

* Orchestrator version (e.g. kubernetes, rkt, swarm, mesos): Kubernetes

* Operating System and version:

```code
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Could you please reopen this issue at github.com/projectcalico/calico? 

This repository is no longer in use.
